name: Build Muse Docker Image

on:
  workflow_dispatch: {}
  push:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v3

      - name: Setup multiarch
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/rdmchr/muse:latest
          build-args: |
            COMMIT_HASH=${{ github.sha }}
            BUILD_DATE=${{ steps.current-time.outputs.time }}